Neos:
  Neos:
    fusion:
      autoInclude:
        NeosRulez.DirectMail.BlogPosts: true
    userInterface:
      translation:
        autoInclude:
          NeosRulez.DirectMail.BlogPosts:
            - 'NodeTypes/*'
